# Generated by Django 5.1.7 on 2025-05-18 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='type',
            field=models.CharField(choices=[('shelter', 'Shelter'), ('evacuation', 'Evacuation'), ('medicine', 'Medicine'), ('food', 'Food'), ('psychological', 'Psychological'), ('clothes', 'Clothes'), ('transport', 'Transport'), ('info_support', 'Info Support'), ('repair', 'Repair'), ('volunteer', 'Volunteer'), ('other', 'Other')], max_length=32),
        ),
    ]
