# Generated by Django 5.1.7 on 2025-05-18 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0002_alter_helprequest_description_alter_helprequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1500)]),
        ),
    ]
