# Generated by Django 5.1.7 on 2025-05-18 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0003_alter_helprequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='contact_phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Введіть правильний номер телефону. Формат: '+380123456789'. До 15 цифр дозволено.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
