# Generated by Django 5.1.7 on 2025-05-18 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0004_alter_helprequest_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='contact_phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Введіть правильний номер телефону у міжнародному форматі. Наприклад: +491234567890', regex='^\\+?[1-9]\\d{7,14}$')]),
        ),
    ]
